export const Amex = {
    Tickers : [
      {
        "key": "AAMC",
        "text": "Altisource Asset Management Corp Com",
        "country": "United States",
        "industry": "Real Estate",
        "sector": "Finance",
      },
      {
        "key": "AAU",
        "text": "Almaden Minerals Ltd. Common Shares",
        "country": "Canada",
        "industry": "",
        "sector": "",
      },
      {
        "key": "ACAQ",
        "text": "Athena Consumer Acquisition Corp. Class A Common Stock",
        "country": "",
        "industry": "Blank Checks",
        "sector": "Finance",
      },
      {
        "key": "ACU",
        "text": "Acme United Corporation. Common Stock",
        "country": "United States",
        "industry": "Industrial Machinery/Components",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "ADEX",
        "text": "Adit EdTech Acquisition Corp. Common Stock",
        "country": "",
        "industry": "EDP Services",
        "sector": "Technology",
      },
      {
        "key": "ADRT",
        "text": "Ault Disruptive Technologies Corporation Common Stock",
        "country": "",
        "industry": "Blank Checks",
        "sector": "Finance",
      },
      {
        "key": "AE",
        "text": "Adams Resources & Energy Inc. Common Stock",
        "country": "United States",
        "industry": "Oil Refining/Marketing",
        "sector": "Energy",
      },
      {
        "key": "AEF",
        "text": "abrdn Emerging Markets Equity Income Fund Inc. Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "AGE",
        "text": "AgeX Therapeutics Inc. Common Stock",
        "country": "",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "AIM",
        "text": "AIM ImmunoTech Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Biological Products (No Diagnostic Substances)",
        "sector": "Health Care",
      },
      {
        "key": "AINC",
        "text": "Ashford Inc. (Holding Company) Common Stock",
        "country": "United States",
        "industry": "Professional Services",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "AIRI",
        "text": "Air Industries Group Common Stock",
        "country": "United States",
        "industry": "Military/Government/Technical",
        "sector": "Industrials",
      },
      {
        "key": "AMBI",
        "text": "Ambipar Emergency Response Class A Ordinary Shares",
        "country": "",
        "industry": "Environmental Services",
        "sector": "Industrials",
      },
      {
        "key": "AMBO",
        "text": "Ambow Education Holding Ltd. American Depository Shares each representing two Class A ordinary shares",
        "country": "China",
        "industry": "Educational Services",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "AMPE",
        "text": "Ampio Pharmaceuticals Inc.",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "AMS",
        "text": "American Shared Hospital Services Common Stock",
        "country": "United States",
        "industry": "Medical Specialities",
        "sector": "Health Care",
      },
      {
        "key": "APT",
        "text": "Alpha Pro Tech Ltd. Common Stock",
        "country": "Canada",
        "industry": "Industrial Specialties",
        "sector": "Health Care",
      },
      {
        "key": "AREN",
        "text": "The Arena Group Holdings Inc. Common Stock",
        "country": "",
        "industry": "Medical/Dental Instruments",
        "sector": "Health Care",
      },
      {
        "key": "ARMP",
        "text": "Armata Pharmaceuticals Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Biological Products (No Diagnostic Substances)",
        "sector": "Health Care",
      },
      {
        "key": "ASM",
        "text": "Avino Silver & Gold Mines Ltd. Common Shares (Canada)",
        "country": "Canada",
        "industry": "Metal Mining",
        "sector": "Basic Materials",
      },
      {
        "key": "ASXC",
        "text": "Asensus Surgical Inc. Common Stock",
        "country": "United States",
        "industry": "Medical/Dental Instruments",
        "sector": "Health Care",
      },
      {
        "key": "ATNM",
        "text": "Actinium Pharmaceuticals Inc. (Delaware) Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "AULT",
        "text": "Ault Alliance Inc. Common Stock",
        "country": "United States",
        "industry": "Industrial Machinery/Components",
        "sector": "Technology",
      },
      {
        "key": "AULT^D",
        "text": "Ault Alliance Inc. 13.00% Series D Cumulative Redeemable Perpetual Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "AUMN",
        "text": "Golden Minerals Company Common Stock",
        "country": "United States",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "AUST",
        "text": "Austin Gold Corp. Common Shares",
        "country": "",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "AWX",
        "text": "Avalon Holdings Corporation Common Stock",
        "country": "United States",
        "industry": "Environmental Services",
        "sector": "Utilities",
      },
      {
        "key": "AZTR",
        "text": "Azitra Inc Common Stock",
        "country": "",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "BACA",
        "text": "Berenson Acquisition Corp. I Class A Common Stock",
        "country": "",
        "industry": "Blank Checks",
        "sector": "Finance",
      },
      {
        "key": "BATL",
        "text": "Battalion Oil Corporation Common Stock",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "BCV",
        "text": "Bancroft Fund Ltd.",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "BCV^A",
        "text": "Bancroft Fund Limited 5.375% Series A Cumulative Preferred Shares",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "BDL",
        "text": "Flanigan's Enterprises Inc. Common Stock",
        "country": "United States",
        "industry": "Restaurants",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "BGI",
        "text": "Birks Group Inc. Common Stock",
        "country": "Canada",
        "industry": "",
        "sector": "",
      },
      {
        "key": "BHB",
        "text": "Bar Harbor Bankshares Inc. Common Stock",
        "country": "United States",
        "industry": "Major Banks",
        "sector": "Finance",
      },
      {
        "key": "BHM",
        "text": "Bluerock Homes Trust Inc. Class A Common Stock",
        "country": "",
        "industry": "Real Estate Investment Trusts",
        "sector": "Real Estate",
      },
      {
        "key": "BITE",
        "text": "Bite Acquisition Corp. Common Stock",
        "country": "",
        "industry": "Blank Checks",
        "sector": "Finance",
      },
      {
        "key": "BKTI",
        "text": "BK Technologies Corporation Common Stock",
        "country": "United States",
        "industry": "Radio And Television Broadcasting And Communications Equipment",
        "sector": "Technology",
      },
      {
        "key": "BLUA",
        "text": "BlueRiver Acquisition Corp. Class A Ordinary Shares",
        "country": "",
        "industry": "Blank Checks",
        "sector": "Finance",
      },
      {
        "key": "BMTX",
        "text": "BM Technologies Inc. Common Stock",
        "country": "",
        "industry": "EDP Services",
        "sector": "Technology",
      },
      {
        "key": "BRBS",
        "text": "Blue Ridge Bankshares Inc. Common Stock",
        "country": "",
        "industry": "Commercial Banks",
        "sector": "Finance",
      },
      {
        "key": "BRN",
        "text": "Barnwell Industries Inc. Common Stock",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "BSAQ",
        "text": "Black Spade Acquisition Co Class A Ordinary Shares",
        "country": "",
        "industry": "Blank Checks",
        "sector": "Finance",
      },
      {
        "key": "BTG",
        "text": "B2Gold Corp Common shares (Canada)",
        "country": "Canada",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "BTTR",
        "text": "Better Choice Company Inc. Common Stock",
        "country": "",
        "industry": "Beverages (Production/Distribution)",
        "sector": "Consumer Staples",
      },
      {
        "key": "BURU",
        "text": "Nuburu Inc. Common Stock",
        "country": "",
        "industry": "Industrial Machinery/Components",
        "sector": "Technology",
      },
      {
        "key": "CANF",
        "text": "Can-Fite Biopharma Ltd Sponsored ADR (Israel)",
        "country": "Israel",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "CATX",
        "text": "Perspective Therapeutics Inc. Common Stock",
        "country": "United States",
        "industry": "Medical/Dental Instruments",
        "sector": "Health Care",
      },
      {
        "key": "CCEL",
        "text": "Cryo-Cell International Inc. Common Stock",
        "country": "United States",
        "industry": "Managed Health Care",
        "sector": "Health Care",
      },
      {
        "key": "CCF",
        "text": "Chase Corporation Common Stock",
        "country": "United States",
        "industry": "Building Products",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "CEI",
        "text": "Camber Energy Inc. Common Stock",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "CET",
        "text": "Central Securities Corporation Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "CEV",
        "text": "Eaton Vance California Municipal Income Trust Shares of Beneficial Interest",
        "country": "United States",
        "industry": "Investment Bankers/Brokers/Service",
        "sector": "Finance",
      },
      {
        "key": "CHAA",
        "text": "Catcha Investment Corp. Class A Ordinary Shares",
        "country": "",
        "industry": "Blank Checks",
        "sector": "Finance",
      },
      {
        "key": "CIK",
        "text": "Credit Suisse Asset Management Income Fund Inc. Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "CIX",
        "text": "CompX International Inc. Common Stock",
        "country": "United States",
        "industry": "Industrial Machinery/Components",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "CKX",
        "text": "CKX Lands Inc. Common Stock",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "CLM",
        "text": "Cornerstone Strategic Value Fund Inc. New Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "CMCL",
        "text": "Caledonia Mining Corporation Plc Common Shares",
        "country": "Canada",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "CMT",
        "text": "Core Molding Technologies Inc Common Stock",
        "country": "United States",
        "industry": "Electronic Components",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "COE",
        "text": "51Talk Online Education Group American depositary shares each representing 60 Class A ordinary shares",
        "country": "China",
        "industry": "Educational Services",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "COHN",
        "text": "Cohen & Company Inc.",
        "country": "United States",
        "industry": "Investment Bankers/Brokers/Service",
        "sector": "Finance",
      },
      {
        "key": "CPHI",
        "text": "China Pharma Holdings Inc. Common Stock",
        "country": "China",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "CQP",
        "text": "Cheniere Energy Partners LP Cheniere Energy Partners LP Common Units",
        "country": "United States",
        "industry": "Oil/Gas Transmission",
        "sector": "Utilities",
      },
      {
        "key": "CRF",
        "text": "Cornerstone Total Return Fund Inc. (The) Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "CTGO",
        "text": "Contango ORE Inc. Common Stock",
        "country": "",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "CTM",
        "text": "Castellum Inc. Common Stock",
        "country": "",
        "industry": "EDP Services",
        "sector": "Technology",
      },
      {
        "key": "CVM",
        "text": "Cel-Sci Corporation Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Biological Products (No Diagnostic Substances)",
        "sector": "Health Care",
      },
      {
        "key": "CVR",
        "text": "Chicago Rivet & Machine Co. Common Stock",
        "country": "United States",
        "industry": "Industrial Machinery/Components",
        "sector": "Industrials",
      },
      {
        "key": "CVU",
        "text": "CPI Aerostructures Inc. Common Stock",
        "country": "United States",
        "industry": "Military/Government/Technical",
        "sector": "Industrials",
      },
      {
        "key": "CYBN",
        "text": "Cybin Inc. Common Shares",
        "country": "Canada",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "DC",
        "text": "Dakota Gold Corp. Common Stock",
        "country": "United States",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "DHY",
        "text": "Credit Suisse High Yield Bond Fund Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "DIT",
        "text": "AMCON Distributing Company Common Stock",
        "country": "United States",
        "industry": "Food Distributors",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "DLA",
        "text": "Delta Apparel Inc. Common Stock",
        "country": "United States",
        "industry": "Apparel",
        "sector": "Consumer Staples",
      },
      {
        "key": "DMF",
        "text": "BNY Mellon Municipal Income Inc. Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "DMYY",
        "text": "dMY Squared Technology Group Inc. Class A Common Stock",
        "country": "",
        "industry": "Blank Checks",
        "sector": "Finance",
      },
      {
        "key": "DNN",
        "text": "Denison Mines Corp Ordinary Shares (Canada)",
        "country": "Canada",
        "industry": "Other Metals and Minerals",
        "sector": "Basic Materials",
      },
      {
        "key": "DPSI",
        "text": "DecisionPoint Systems Inc. Common Stock",
        "country": "",
        "industry": "Retail: Computer Software & Peripheral Equipment",
        "sector": "Technology",
      },
      {
        "key": "DSS",
        "text": "DSS Inc. Common Stock",
        "country": "United States",
        "industry": "Containers/Packaging",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "DXF",
        "text": "Dunxin Financial Holdings Limited American Depositary Shares",
        "country": "China",
        "industry": "Finance: Consumer Services",
        "sector": "Finance",
      },
      {
        "key": "EAD",
        "text": "Allspring Income Opportunities Fund Common Shares",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "ECF",
        "text": "Ellsworth Growth and Income Fund Ltd.",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "ECF^A",
        "text": "Ellsworth Growth and Income Fund Ltd. 5.25% Series A Cumulative Preferred Shares (Liquidation Preference $25.00 per share)",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "EFSH",
        "text": "1847 Holdings LLC Common Shares",
        "country": "",
        "industry": "Professional Services",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "EIM",
        "text": "Eaton Vance Municipal Bond Fund Common Shares of Beneficial Interest $.01 par value",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "ELA",
        "text": "Envela Corporation Common Stock",
        "country": "United States",
        "industry": "Consumer Specialties",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "ELLO",
        "text": "Ellomay Capital Ltd Ordinary Shares (Israel)",
        "country": "Israel",
        "industry": "Electric Utilities: Central",
        "sector": "Utilities",
      },
      {
        "key": "ELMD",
        "text": "Electromed Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Electromedical & Electrotherapeutic Apparatus",
        "sector": "Health Care",
      },
      {
        "key": "EMAN",
        "text": "eMagin Corporation Common Stock",
        "country": "United States",
        "industry": "Industrial Machinery/Components",
        "sector": "Technology",
      },
      {
        "key": "EMX",
        "text": "EMX Royalty Corporation Common Shares (Canada)",
        "country": "Canada",
        "industry": "",
        "sector": "",
      },
      {
        "key": "ENSV",
        "text": "Enservco Corporation Common Stock",
        "country": "United States",
        "industry": "Oilfield Services/Equipment",
        "sector": "Energy",
      },
      {
        "key": "ENX",
        "text": "Eaton Vance New York Municipal Bond Fund Common Shares of Beneficial Interest $.01 par value",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "EP",
        "text": "Empire Petroleum Corporation Common Stock",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "EPM",
        "text": "Evolution Petroleum Corporation Inc. Common Stock",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "EQX",
        "text": "Equinox Gold Corp. Common Shares",
        "country": "Canada",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "ERC",
        "text": "Allspring Multi-Sector Income Fund Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "ERH",
        "text": "Allspring Utilities and High Income Fund Common Shares",
        "country": "",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "ESP",
        "text": "Espey Mfg. & Electronics Corp. Common Stock",
        "country": "United States",
        "industry": "Industrial Machinery/Components",
        "sector": "Technology",
      },
      {
        "key": "EU",
        "text": "enCore Energy Corp. Common Shares",
        "country": "",
        "industry": "Other Metals and Minerals",
        "sector": "Basic Materials",
      },
      {
        "key": "EVBN",
        "text": "Evans Bancorp Inc. Common Stock",
        "country": "United States",
        "industry": "Major Banks",
        "sector": "Finance",
      },
      {
        "key": "EVE",
        "text": "EVe Mobility Acquisition Corp Class A Ordinary Shares",
        "country": "",
        "industry": "Blank Checks",
        "sector": "Finance",
      },
      {
        "key": "EVI",
        "text": "EVI Industries Inc.  Common Stock",
        "country": "United States",
        "industry": "Other Consumer Services",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "EVM",
        "text": "Eaton Vance California Municipal Bond Fund Common Shares of Beneficial Interest $.01 par value",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "EVV",
        "text": "Eaton Vance Limited Duration Income Fund Common Shares of Beneficial Interest",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "FAX",
        "text": "abrdn Asia-Pacific Income Fund Inc. Common Stock",
        "country": "United States",
        "industry": "Investment Managers",
        "sector": "Finance",
      },
      {
        "key": "FCO",
        "text": "abrdn Global Income Fund Inc. Common Stock",
        "country": "United States",
        "industry": "Investment Managers",
        "sector": "Finance",
      },
      {
        "key": "FEN",
        "text": "First Trust Energy Income and Growth Fund",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "FGH",
        "text": "FG Group Holdings Inc. Common Stock",
        "country": "United States",
        "industry": "Industrial Machinery/Components",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "FLAG",
        "text": "First Light Acquisition Group Inc. Class A Common Stock",
        "country": "",
        "industry": "Biotechnology: Biological Products (No Diagnostic Substances)",
        "sector": "Health Care",
      },
      {
        "key": "FOXO",
        "text": "FOXO Technologies Inc. Class A Common Stock",
        "country": "",
        "industry": "Retail: Computer Software & Peripheral Equipment",
        "sector": "Technology",
      },
      {
        "key": "FRD",
        "text": "Friedman Industries Inc. Common Stock",
        "country": "United States",
        "industry": "Steel/Iron Ore",
        "sector": "Industrials",
      },
      {
        "key": "FSI",
        "text": "Flexible Solutions International Inc. Common Stock (CDA)",
        "country": "Canada",
        "industry": "Major Chemicals",
        "sector": "Industrials",
      },
      {
        "key": "FSP",
        "text": "Franklin Street Properties Corp. Common Stock",
        "country": "United States",
        "industry": "Real Estate Investment Trusts",
        "sector": "Real Estate",
      },
      {
        "key": "FTF",
        "text": "Franklin Limited Duration Income Trust Common Shares of Beneficial Interest",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "FURY",
        "text": "Fury Gold Mines Limited Common Shares",
        "country": "",
        "industry": "",
        "sector": "",
      },
      {
        "key": "GAU",
        "text": "Galiano Gold Inc.",
        "country": "Canada",
        "industry": "",
        "sector": "",
      },
      {
        "key": "GBR",
        "text": "New Concept Energy Inc Common Stock",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "GENC",
        "text": "Gencor Industries Inc. Common Stock",
        "country": "United States",
        "industry": "Construction/Ag Equipment/Trucks",
        "sector": "Industrials",
      },
      {
        "key": "GGN",
        "text": "GAMCO Global Gold Natural Resources & Income Trust",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "GGN^B",
        "text": "GAMCO Global Gold Natural Reources & Income Trust 5.00% Series B Cumulative 25.00 Liquidation Preference",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "GLDG",
        "text": "GoldMining Inc. Common Shares",
        "country": "",
        "industry": "",
        "sector": "",
      },
      {
        "key": "GLO",
        "text": "Clough Global Opportunities Fund Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "GLQ",
        "text": "Clough Global Equity Fund Clough Global Equity Fund Common Shares of Beneficial Interest",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "GLU",
        "text": "Gabelli Global Utility Common Shares of Beneficial Ownership",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "GLU^B",
        "text": "The Gabelli Global Utility and Income Trust Series B Cumulative Puttable and Callable Preferred Shares",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "GLV",
        "text": "Clough Global Dividend and Income Fund Common Shares of beneficial interest",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "GNS",
        "text": "Genius Group Limited Ordinary Shares",
        "country": "",
        "industry": "Educational Services",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "GORO",
        "text": "Gold Resource Corporation Common Stock",
        "country": "United States",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "GRF",
        "text": "Eagle Capital Growth Fund Inc. Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "GRFX",
        "text": "Graphex Group Limited American Depositary Shares each American Depositary Share representing 20 Ordinary Shares",
        "country": "",
        "industry": "",
        "sector": "",
      },
      {
        "key": "GROY",
        "text": "Gold Royalty Corp. Common Shares",
        "country": "Canada",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "GSAT",
        "text": "Globalstar Inc. Common Stock",
        "country": "United States",
        "industry": "Telecommunications Equipment",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "GTE",
        "text": "Gran Tierra Energy Inc. Common Stock",
        "country": "Canada",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "HNRA",
        "text": "HNR Acquisition Corp Common Stock",
        "country": "",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "HNW",
        "text": "Pioneer Diversified High Income Fund Inc.",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "HUSA",
        "text": "Houston American Energy Corporation Common Stock",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "HWM^",
        "text": "Howmet Aerospace Inc. $3.75 Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "IAF",
        "text": "abrdn Australia Equity Fund Inc. Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "IAUX",
        "text": "i-80 Gold Corp. Common Shares",
        "country": "",
        "industry": "",
        "sector": "",
      },
      {
        "key": "IBIO",
        "text": "iBio Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "ID",
        "text": "PARTS iD Inc. Class A Common Stock",
        "country": "United States",
        "industry": "Diversified Commercial Services",
        "sector": "Miscellaneous",
      },
      {
        "key": "IDR",
        "text": "Idaho Strategic Resources Inc. Common Stock",
        "country": "",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "IE",
        "text": "Ivanhoe Electric Inc. Common Stock",
        "country": "",
        "industry": "Metal Mining",
        "sector": "Basic Materials",
      },
      {
        "key": "IGC",
        "text": "IGC Pharma Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "IHT",
        "text": "InnSuites Hospitality Trust Shares of Beneficial Interest",
        "country": "United States",
        "industry": "Investment Bankers/Brokers/Service",
        "sector": "Finance",
      },
      {
        "key": "IMO",
        "text": "Imperial Oil Limited Common Stock",
        "country": "Canada",
        "industry": "",
        "sector": "",
      },
      {
        "key": "INDO",
        "text": "Indonesia Energy Corporation Limited Ordinary Shares",
        "country": "",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "INFU",
        "text": "InfuSystems Holdings Inc. Common Stock",
        "country": "United States",
        "industry": "Medical/Dental Instruments",
        "sector": "Health Care",
      },
      {
        "key": "INLX",
        "text": "Intellinetics Inc. Common Stock",
        "country": "",
        "industry": "Computer Software: Prepackaged Software",
        "sector": "Technology",
      },
      {
        "key": "INTT",
        "text": "inTest Corporation Common Stock",
        "country": "United States",
        "industry": "Electrical Products",
        "sector": "Industrials",
      },
      {
        "key": "INUV",
        "text": "Inuvo Inc.",
        "country": "United States",
        "industry": "Advertising",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "IOR",
        "text": "Income Opportunity Realty Investors Inc. Common Stock",
        "country": "United States",
        "industry": "Real Estate Investment Trusts",
        "sector": "Real Estate",
      },
      {
        "key": "IPVF",
        "text": "InterPrivate III Financial Partners Inc. Class A Common Stock",
        "country": "",
        "industry": "Investment Bankers/Brokers/Service",
        "sector": "Finance",
      },
      {
        "key": "ISDR",
        "text": "Issuer Direct Corporation Common Stock",
        "country": "United States",
        "industry": "Publishing",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "ITP",
        "text": "IT Tech Packaging Inc. Common Stock",
        "country": "China",
        "industry": "Containers/Packaging",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "ITRG",
        "text": "Integra Resources Corp. Common Shares",
        "country": "",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "JOB",
        "text": "GEE Group Inc. Common Stock",
        "country": "United States",
        "industry": "Diversified Commercial Services",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "JWSM",
        "text": "Jaws Mustang Acquisition Corp. Class A Ordinary Shares",
        "country": "",
        "industry": "Blank Checks",
        "sector": "Finance",
      },
      {
        "key": "KIQ",
        "text": "Kelso Technologies Inc Ordinary Shares",
        "country": "Canada",
        "industry": "Railroads",
        "sector": "Industrials",
      },
      {
        "key": "KNW",
        "text": "Know Labs Inc. Common Stock",
        "country": "",
        "industry": "Industrial Machinery/Components",
        "sector": "Industrials",
      },
      {
        "key": "KULR",
        "text": "KULR Technology Group Inc. Common Stock",
        "country": "United States",
        "industry": "Electrical Products",
        "sector": "Technology",
      },
      {
        "key": "LCTX",
        "text": "Lineage Cell Therapeutics Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Biological Products (No Diagnostic Substances)",
        "sector": "Health Care",
      },
      {
        "key": "LEU",
        "text": "Centrus Energy Corp. Class A Common Stock",
        "country": "United States",
        "industry": "Mining & Quarrying of Nonmetallic Minerals (No Fuels)",
        "sector": "Industrials",
      },
      {
        "key": "LGL",
        "text": "LGL Group Inc. (The) Common Stock",
        "country": "United States",
        "industry": "Industrial Machinery/Components",
        "sector": "Technology",
      },
      {
        "key": "LNG",
        "text": "Cheniere Energy Inc. Common Stock",
        "country": "United States",
        "industry": "Oil/Gas Transmission",
        "sector": "Utilities",
      },
      {
        "key": "LODE",
        "text": "Comstock Inc. Common Stock",
        "country": "United States",
        "industry": "Major Chemicals",
        "sector": "Industrials",
      },
      {
        "key": "LPTV",
        "text": "Loop Media Inc. Common Stock",
        "country": "",
        "industry": "Broadcasting",
        "sector": "Industrials",
      },
      {
        "key": "LSF",
        "text": "Laird Superfood Inc. Common Stock",
        "country": "",
        "industry": "Packaged Foods",
        "sector": "Consumer Staples",
      },
      {
        "key": "LXFR",
        "text": "Luxfer Holdings PLC Ordinary Shares",
        "country": "United Kingdom",
        "industry": "Major Chemicals",
        "sector": "Industrials",
      },
      {
        "key": "MAG",
        "text": "MAG Silver Corporation Ordinary Shares",
        "country": "Canada",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "MAIA",
        "text": "MAIA Biotechnology Inc. Common Stock",
        "country": "",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "MGLD",
        "text": "The Marygold Companies Inc. Common Stock",
        "country": "",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "MHH",
        "text": "Mastech Digital Inc Common Stock",
        "country": "United States",
        "industry": "Professional Services",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "MIMO",
        "text": "Airspan Networks Holdings Inc. Common Stock",
        "country": "",
        "industry": "Telecommunications Equipment",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "MITQ",
        "text": "Moving iMage Technologies Inc. Common Stock",
        "country": "United States",
        "industry": "Telecommunications Equipment",
        "sector": "Telecommunications",
      },
      {
        "key": "MLSS",
        "text": "Milestone Scientific Inc. Common Stock",
        "country": "United States",
        "industry": "Industrial Specialties",
        "sector": "Health Care",
      },
      {
        "key": "MNK",
        "text": "Mallinckrodt plc Ordinary Shares",
        "country": "",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "MPTI",
        "text": "M-tron Industries Inc. Common Stock",
        "country": "",
        "industry": "",
        "sector": "",
      },
      {
        "key": "MPU",
        "text": "Mega Matrix Corp. Common Stock",
        "country": "United States",
        "industry": "Transportation Services",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "MRT",
        "text": "Marti Technologies Inc. Class A Ordinary Shares",
        "country": "",
        "industry": "Rental/Leasing Companies",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "MSN",
        "text": "Emerson Radio Corporation Common Stock",
        "country": "United States",
        "industry": "Consumer Electronics/Appliances",
        "sector": "Consumer Staples",
      },
      {
        "key": "MTA",
        "text": "Metalla Royalty & Streaming Ltd. Common Shares",
        "country": "",
        "industry": "",
        "sector": "",
      },
      {
        "key": "MTNB",
        "text": "Matinas Biopharma Holdings Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "MWG",
        "text": "Multi Ways Holdings Limited Ordinary Shares",
        "country": "",
        "industry": "Miscellaneous manufacturing industries",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "MXC",
        "text": "Mexco Energy Corporation Common Stock",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "MYO",
        "text": "Myomo Inc. Common Stock",
        "country": "United States",
        "industry": "Industrial Specialties",
        "sector": "Health Care",
      },
      {
        "key": "NAK",
        "text": "Northern Dynasty Minerals Ltd. Common Stock",
        "country": "Canada",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "NAVB",
        "text": "Navidea Biopharmaceuticals Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: In Vitro & In Vivo Diagnostic Substances",
        "sector": "Health Care",
      },
      {
        "key": "NBH",
        "text": "Neuberger Berman Municipal Fund Inc. Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "NBO",
        "text": "Neuberger Berman New York Municipal Fund Inc. Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "NBW",
        "text": "Neuberger Berman California Municipal Fund Inc Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "NBY",
        "text": "NovaBay Pharmaceuticals Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "NEN",
        "text": "New England Realty Associates Limited Partnership Class A Depositary Receipts Evidencing Units of Limited Partnership",
        "country": "United States",
        "industry": "Real Estate",
        "sector": "Finance",
      },
      {
        "key": "NEWP",
        "text": "New Pacific Metals Corp. Common Shares",
        "country": "",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "NFGC",
        "text": "New Found Gold Corp Common Shares",
        "country": "",
        "industry": "",
        "sector": "",
      },
      {
        "key": "NG",
        "text": "Novagold Resources Inc.",
        "country": "Canada",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "NGD",
        "text": "New Gold Inc.",
        "country": "Canada",
        "industry": "",
        "sector": "",
      },
      {
        "key": "NHC",
        "text": "National HealthCare Corporation Common Stock",
        "country": "United States",
        "industry": "Hospital/Nursing Management",
        "sector": "Health Care",
      },
      {
        "key": "NHS",
        "text": "Neuberger Berman High Yield Strategies Fund",
        "country": "United States",
        "industry": "Trusts Except Educational Religious and Charitable",
        "sector": "Finance",
      },
      {
        "key": "NHWK",
        "text": "NightHawk Biosciences Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "NML",
        "text": "Neuberger Berman Energy Infrastructure and Income Fund Inc. Common Stock",
        "country": "",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "NNVC",
        "text": "NanoViricides Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "NRO",
        "text": "Neuberger Berman Real Estate Securities Income Fund Inc. Neuberger Berman Real Estate Securities Income Fund Inc.",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "NSTB",
        "text": "Northern Star Investment Corp. II Class A Common stock",
        "country": "",
        "industry": "Investment Bankers/Brokers/Service",
        "sector": "Finance",
      },
      {
        "key": "NTIP",
        "text": "Network-1 Technologies Inc. Common Stock",
        "country": "United States",
        "industry": "Multi-Sector Companies",
        "sector": "Miscellaneous",
      },
      {
        "key": "OBE",
        "text": "Obsidian Energy Ltd. Common Shares",
        "country": "Canada",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "OGEN",
        "text": "Oragenics Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "OPTT",
        "text": "Ocean Power Technologies Inc. Common Stock",
        "country": "United States",
        "industry": "Industrial Machinery/Components",
        "sector": "Industrials",
      },
      {
        "key": "ORLA",
        "text": "Orla Mining Ltd. Common Shares",
        "country": "",
        "industry": "",
        "sector": "",
      },
      {
        "key": "OZ",
        "text": "Belpointe PREP LLC Class A Units",
        "country": "",
        "industry": "",
        "sector": "",
      },
      {
        "key": "PCG^A",
        "text": "Pacific Gas & Electric Co. 6% Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "PCG^B",
        "text": "Pacific Gas & Electric Co. 5 1/2% Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "PCG^C",
        "text": "Pacific Gas & Electric Co. 5% 1st Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "PCG^D",
        "text": "Pacific Gas & Electric Co. 5% 1st  Red. Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "PCG^E",
        "text": "Pacific Gas & Electric Co. 5% 1st A Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "PCG^G",
        "text": "Pacific Gas & Electric Co. 4.80% 1st Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "PCG^H",
        "text": "Pacific Gas & Electric Co. 4.50% 1st Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "PCG^I",
        "text": "Pacific Gas & Electric Co. 4.36% 1st Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "PED",
        "text": "Pedevco Corp. Common Stock",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "PHGE",
        "text": "BiomX Inc. COmmon Stock",
        "country": "",
        "industry": "Biotechnology: Biological Products (No Diagnostic Substances)",
        "sector": "Health Care",
      },
      {
        "key": "PLAG",
        "text": "Planet Green Holdings Corp. Common Stock",
        "country": "China",
        "industry": "Packaged Foods",
        "sector": "Consumer Staples",
      },
      {
        "key": "PLG",
        "text": "Platinum Group Metals Ltd. Ordinary Shares (Canada)",
        "country": "Canada",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "PLM",
        "text": "Polymet Mining Corporation Ordinary Shares (Canada)",
        "country": "Canada",
        "industry": "",
        "sector": "",
      },
      {
        "key": "PLX",
        "text": "Protalix BioTherapeutics Inc. (DE) Common Stock",
        "country": "Israel",
        "industry": "Biotechnology: Biological Products (No Diagnostic Substances)",
        "sector": "Health Care",
      },
      {
        "key": "PLYM^A",
        "text": "Plymouth Industrial REIT Inc. 7.50% Series A Cumulative Redeemable Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "POL",
        "text": "Polished Inc. Common Stock",
        "country": "United States",
        "industry": "Home Furnishings",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "PRK",
        "text": "Park National Corporation Common Stock",
        "country": "United States",
        "industry": "Major Banks",
        "sector": "Finance",
      },
      {
        "key": "PTN",
        "text": "Palatin Technologies Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "PW",
        "text": "Power REIT (MD) Common Stock",
        "country": "United States",
        "industry": "Real Estate Investment Trusts",
        "sector": "Real Estate",
      },
      {
        "key": "PW^A",
        "text": "Power REIT 7.75% Series A Cumulative Perpetual Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "PZG",
        "text": "Paramount Gold Nevada Corp. Common Stock",
        "country": "United States",
        "industry": "Metal Mining",
        "sector": "Basic Materials",
      },
      {
        "key": "RCG",
        "text": "RENN Fund Inc Common Stock",
        "country": "United States",
        "industry": "Investment Managers",
        "sector": "Finance",
      },
      {
        "key": "REI",
        "text": "Ring Energy Inc. Common Stock",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "REPX",
        "text": "Riley Exploration Permian Inc. Common Stock",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "RHE",
        "text": "Regional Health Properties Inc. Common Stock",
        "country": "",
        "industry": "Real Estate",
        "sector": "Real Estate",
      },
      {
        "key": "RHE^A",
        "text": "Regional Health Properties Inc. 10.875% Series A Cumulative Redeemable Preferred Stock",
        "country": "",
        "industry": "",
        "sector": "",
      },
      {
        "key": "RLGT",
        "text": "Radiant Logistics Inc. Common Stock",
        "country": "United States",
        "industry": "Oil Refining/Marketing",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "RMED",
        "text": "Ra Medical Systems Inc. Common Stock",
        "country": "",
        "industry": "Medical/Dental Instruments",
        "sector": "Health Care",
      },
      {
        "key": "RVP",
        "text": "Retractable Technologies Inc. Common Stock",
        "country": "United States",
        "industry": "Medical/Dental Instruments",
        "sector": "Health Care",
      },
      {
        "key": "SACC",
        "text": "Sachem Capital Corp. 6.875% Notes due 2024",
        "country": "United States",
        "industry": "Real Estate Investment Trusts",
        "sector": "Real Estate",
      },
      {
        "key": "SACH",
        "text": "Sachem Capital Corp. Common Shares",
        "country": "United States",
        "industry": "Real Estate Investment Trusts",
        "sector": "Real Estate",
      },
      {
        "key": "SACH^A",
        "text": "Sachem Capital Corp. 7.75% Series A Cumulative Redeemable Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "SATX",
        "text": "SatixFy Communications Ltd. Ordinary Share",
        "country": "",
        "industry": "Radio And Television Broadcasting And Communications Equipment",
        "sector": "Technology",
      },
      {
        "key": "SBEV",
        "text": "Splash Beverage Group Inc. (NV) Common Stock",
        "country": "",
        "industry": "Beverages (Production/Distribution)",
        "sector": "Consumer Staples",
      },
      {
        "key": "SCCB",
        "text": "Sachem Capital Corp. 7.125% Notes due 2024",
        "country": "United States",
        "industry": "Real Estate Investment Trusts",
        "sector": "Real Estate",
      },
      {
        "key": "SCCC",
        "text": "Sachem Capital Corp. 7.75% Notes due 2025",
        "country": "United States",
        "industry": "Real Estate Investment Trusts",
        "sector": "Real Estate",
      },
      {
        "key": "SCCD",
        "text": "Sachem Capital Corp. 6.00% Notes due 2026",
        "country": "United States",
        "industry": "Real Estate Investment Trusts",
        "sector": "Real Estate",
      },
      {
        "key": "SCCE",
        "text": "Sachem Capital Corp. 6.00% Notes due 2027",
        "country": "United States",
        "industry": "Real Estate Investment Trusts",
        "sector": "Real Estate",
      },
      {
        "key": "SCCF",
        "text": "Sachem Capital Corp. 7.125% Notes due 2027",
        "country": "United States",
        "industry": "Real Estate Investment Trusts",
        "sector": "Real Estate",
      },
      {
        "key": "SCCG",
        "text": "Sachem Capital Corp. 8.00% Notes due 2027",
        "country": "United States",
        "industry": "Real Estate Investment Trusts",
        "sector": "Real Estate",
      },
      {
        "key": "SDPI",
        "text": "Superior Drilling Products Inc. Common Stock",
        "country": "",
        "industry": "Metal Fabrications",
        "sector": "Industrials",
      },
      {
        "key": "SEB",
        "text": "Seaboard Corporation Common Stock",
        "country": "United States",
        "industry": "Farming/Seeds/Milling",
        "sector": "Industrials",
      },
      {
        "key": "SENS",
        "text": "Senseonics Holdings Inc. Common Stock",
        "country": "United States",
        "industry": "Industrial Machinery/Components",
        "sector": "Industrials",
      },
      {
        "key": "SGE",
        "text": "Strong Global Entertainment Inc. Class A Common Voting Shares",
        "country": "",
        "industry": "Industrial Machinery/Components",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "SIF",
        "text": "SIFCO Industries Inc. Common Stock",
        "country": "United States",
        "industry": "Aerospace",
        "sector": "Industrials",
      },
      {
        "key": "SILV",
        "text": "SilverCrest Metals Inc. Common Shares",
        "country": "",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "SIM",
        "text": "Grupo Simec S.A.B. de C.V. American Depositary Shares",
        "country": "Mexico",
        "industry": "Steel/Iron Ore",
        "sector": "Industrials",
      },
      {
        "key": "SKYH",
        "text": "Sky Harbour Group Corporation Class A Common Stock",
        "country": "",
        "industry": "Military/Government/Technical",
        "sector": "Industrials",
      },
      {
        "key": "SLI",
        "text": "Standard Lithium Ltd. Common Shares",
        "country": "Canada",
        "industry": "",
        "sector": "",
      },
      {
        "key": "SLND",
        "text": "Southland Holdings Inc. Common Stock",
        "country": "United States",
        "industry": "Military/Government/Technical",
        "sector": "Industrials",
      },
      {
        "key": "SSY",
        "text": "SunLink Health Systems Inc. Common Stock",
        "country": "United States",
        "industry": "Hospital/Nursing Management",
        "sector": "Health Care",
      },
      {
        "key": "STRW",
        "text": "Strawberry Fields REIT Inc. Common Stock",
        "country": "",
        "industry": "Real Estate Investment Trusts",
        "sector": "Real Estate",
      },
      {
        "key": "STXS",
        "text": "Stereotaxis Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Electromedical & Electrotherapeutic Apparatus",
        "sector": "Health Care",
      },
      {
        "key": "SVM",
        "text": "Silvercorp Metals Inc. Common Shares",
        "country": "",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "SVT",
        "text": "Servotronics Inc. Common Stock",
        "country": "United States",
        "industry": "Industrial Machinery/Components",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "TELL",
        "text": "Tellurian Inc. Common Stock",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "TELZ",
        "text": "Tellurian Inc. 8.25% Senior Notes due 2028",
        "country": "United States",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "TGB",
        "text": "Taseko Mines Ltd. Common Stock",
        "country": "Canada",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "THM",
        "text": "International Tower Hill Mines Ltd. Ordinary Shares (Canada)",
        "country": "Canada",
        "industry": "Metal Mining",
        "sector": "Basic Materials",
      },
      {
        "key": "TKAT",
        "text": "Takung Art Co. Ltd. Common Stock",
        "country": "",
        "industry": "Other Specialty Stores",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "TMBR",
        "text": "Timber Pharmaceuticals Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "TMP",
        "text": "Tompkins Financial Corporation Common Stock",
        "country": "United States",
        "industry": "Major Banks",
        "sector": "Finance",
      },
      {
        "key": "TMQ",
        "text": "Trilogy Metals Inc. Common Stock",
        "country": "Canada",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "TOON",
        "text": "Kartoon Studios Inc. Common Stock",
        "country": "United States",
        "industry": "Movies/Entertainment",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "TOVX",
        "text": "Theriva Biologics Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "TPET",
        "text": "Trio Petroleum Corp. Common Stock",
        "country": "",
        "industry": "Oil & Gas Production",
        "sector": "Energy",
      },
      {
        "key": "TPHS",
        "text": "Trinity Place Holdings Inc. Common Stock",
        "country": "",
        "industry": "Building operators",
        "sector": "Real Estate",
      },
      {
        "key": "TRT",
        "text": "Trio-Tech International Common Stock",
        "country": "United States",
        "industry": "Industrial Machinery/Components",
        "sector": "Technology",
      },
      {
        "key": "TRX",
        "text": "TRX Gold Corporation Common Stock",
        "country": "Canada",
        "industry": "",
        "sector": "",
      },
      {
        "key": "UAMY",
        "text": "United States Antimony Corporation Common Stock",
        "country": "United States",
        "industry": "Metal Fabrications",
        "sector": "Industrials",
      },
      {
        "key": "UAVS",
        "text": "AgEagle Aerial Systems Inc. Common Stock",
        "country": "United States",
        "industry": "Aerospace",
        "sector": "Industrials",
      },
      {
        "key": "UEC",
        "text": "Uranium Energy Corp. Common Stock",
        "country": "Canada",
        "industry": "Other Metals and Minerals",
        "sector": "Basic Materials",
      },
      {
        "key": "UFAB",
        "text": "Unique Fabricating Inc. Common Stock",
        "country": "United States",
        "industry": "Auto Parts:O.E.M.",
        "sector": "Consumer Discretionary",
      },
      {
        "key": "URG",
        "text": "Ur Energy Inc Common Shares (Canada)",
        "country": "Canada",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "USAS",
        "text": "Americas Gold and Silver Corporation Common Shares no par value",
        "country": "",
        "industry": "Metal Mining",
        "sector": "Basic Materials",
      },
      {
        "key": "UTG",
        "text": "Reaves Utility Income Fund Common Shares of Beneficial Interest",
        "country": "United States",
        "industry": "Investment Managers",
        "sector": "Finance",
      },
      {
        "key": "UUU",
        "text": "Universal Security Instruments Inc. Common Stock",
        "country": "United States",
        "industry": "Electronic Components",
        "sector": "Technology",
      },
      {
        "key": "UUUU",
        "text": "Energy Fuels Inc Ordinary Shares (Canada)",
        "country": "",
        "industry": "Mining & Quarrying of Nonmetallic Minerals (No Fuels)",
        "sector": "Industrials",
      },
      {
        "key": "VFL",
        "text": "abrdn National Municipal Income Fund Common Stock",
        "country": "United States",
        "industry": "Finance/Investors Services",
        "sector": "Finance",
      },
      {
        "key": "VGZ",
        "text": "Vista Gold Corp Common Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "VHAQ",
        "text": "Viveon Health Acquisition Corp. Common Stock",
        "country": "",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "VINE",
        "text": "Fresh Vine Wine Inc. Common Stock",
        "country": "",
        "industry": "Beverages (Production/Distribution)",
        "sector": "Consumer Staples",
      },
      {
        "key": "VKI",
        "text": "Invesco Advantage Municipal Income Trust II Common Shares of Beneficial Interest (DE)",
        "country": "United States",
        "industry": "Finance Companies",
        "sector": "Finance",
      },
      {
        "key": "VNRX",
        "text": "VolitionRX Limited Common Stock",
        "country": "Singapore",
        "industry": "Biotechnology: Biological Products (No Diagnostic Substances)",
        "sector": "Health Care",
      },
      {
        "key": "VZLA",
        "text": "Vizsla Silver Corp. Common Shares",
        "country": "",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "WLMS",
        "text": "Williams Industrial Services Group Inc. Common Stock",
        "country": "",
        "industry": "Military/Government/Technical",
        "sector": "Industrials",
      },
      {
        "key": "WRAC",
        "text": "Williams Rowland Acquisition Corp. Common Stock",
        "country": "",
        "industry": "Blank Checks",
        "sector": "Finance",
      },
      {
        "key": "WRN",
        "text": "Western Copper and Gold Corporation Common Stock",
        "country": "Canada",
        "industry": "Metal Mining",
        "sector": "Basic Materials",
      },
      {
        "key": "WTT",
        "text": "Wireless Telecom Group  Inc. Common Stock",
        "country": "United States",
        "industry": "Telecommunications Equipment",
        "sector": "Telecommunications",
      },
      {
        "key": "WWR",
        "text": "Westwater Resources Inc. Common Stock",
        "country": "United States",
        "industry": "Metal Mining",
        "sector": "Basic Materials",
      },
      {
        "key": "WYY",
        "text": "WidePoint Corporation Common Stock",
        "country": "United States",
        "industry": "EDP Services",
        "sector": "Technology",
      },
      {
        "key": "XPL",
        "text": "Solitario Zinc Corp. Common Stock",
        "country": "United States",
        "industry": "Precious Metals",
        "sector": "Basic Materials",
      },
      {
        "key": "XTNT",
        "text": "Xtant Medical Holdings Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Biological Products (No Diagnostic Substances)",
        "sector": "Health Care",
      },
      {
        "key": "YCBD",
        "text": "cbdMD Inc. Common Stock",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      },
      {
        "key": "YCBD^A",
        "text": "cbdMD Inc. 8.0% Series A Cumulative Convertible Preferred Stock",
        "country": "United States",
        "industry": "",
        "sector": "",
      },
      {
        "key": "ZDGE",
        "text": "Zedge Inc. Class B Common Stock ",
        "country": "",
        "industry": "Computer Software: Prepackaged Software",
        "sector": "Technology",
      },
      {
        "key": "ZOM",
        "text": "Zomedica Corp. Common Shares",
        "country": "United States",
        "industry": "Biotechnology: Pharmaceutical Preparations",
        "sector": "Health Care",
      }
      ]
      
}
export default Amex;